---
- hosts: mywebserver
  become: yes
  tasks:
    - name : i want to run linux command on ansible node
      command: hostname -f
      register: myResult 

    - name: i want to display result of linux command
      debug:
       msg: "{{myResult}}"

    - name: i want to install git
      apt:
       name: git
       state: prsent
      when: myResult.stderr == ""

    - name: i want to display result of linux command
      apt:
       name: wget 
       state: prsent
      when: myResult.stderr != ""